[project]
name = "zen-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "fastmcp",
    "orjson>=3.11.0",
    "pytest",
    "rich",
    "uvicorn[standard]>=0.30.0",
]
